"""Where things are, and what hardware we are on. Deliberately NOT hyperparameters.

Tunables stay hard-coded in the module that uses them — sigma in codec/encode.py, lr and
epochs in train.py, the percentile list in analyze_labels.py. The knob sits next to the
code it controls, and no config schema has to be designed before we know which knobs
actually matter.

The cost, accepted knowingly: answering "which settings produced this checkpoint" is
harder with module-local constants than with one frozen dataclass. When that starts to
hurt, gather the constants that turned out to matter into a dataclass then, rather than
guessing at them now.

The one value worth watching is STRIDE: codec/encode.py, codec/decode.py, model/neck.py
and data/dataset.py all use it and they must agree. If hard-coding it four times starts
to feel fragile, it belongs here.
"""

import os

# Everything is anchored to the repo root, derived from this file's own location, so
# scripts work regardless of the working directory they were launched from.
REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASETS_DIR = os.path.join(REPO_ROOT, 'datasets')
OUTPUTS_DIR = os.path.join(REPO_ROOT, 'centerpoint', 'outputs')

# The dataset every script defaults to. v30 while developing: it is clean and easy, and
# YOLO26 reached 99.3% mAP50 on it, so a bad number there means a bug in our code rather
# than a hard image. Point this at bullet_rchsr/clean for real training, and pass that
# path explicitly before trusting any stride or sigma choice — see PLAN.md.
DATASET = os.path.join(DATASETS_DIR, 'bullet_holes', 'clean_v30')

EXAMPLES_DIR = os.path.join(DATASETS_DIR, 'examples')


def output_dir(*parts):
    """Path under centerpoint/outputs/, created if missing."""
    path = os.path.join(OUTPUTS_DIR, *parts)
    os.makedirs(path, exist_ok=True)
    return path


def dataset_name(dataset_root):
    """A filesystem-safe name for a dataset root, e.g. 'bullet_rchsr_clean'."""
    rel = os.path.relpath(os.path.abspath(dataset_root), DATASETS_DIR)
    if rel.startswith('..'):                       # a root outside datasets/
        rel = os.path.basename(os.path.abspath(dataset_root))
    return rel.replace(os.sep, '_')


def debug_dir(kind, dataset_root):
    """outputs/debug/<kind>/<dataset>/ — development artefacts, safe to delete wholesale.

    Everything under debug/ is regenerated by re-running the script that made it, so the
    whole directory can go at any time. Trained models and evaluation results will live
    elsewhere under outputs/, and those are not disposable.

    The per-dataset level is not optional: without it two datasets' renders land in the
    same folder and silently mix, which is what happened the first time analyze_labels.py
    was run.
    """
    return output_dir('debug', kind, dataset_name(dataset_root))


def resolve_device():
    """'xpu', 'cuda' or 'cpu' — resolved at runtime, never hardcoded.

    This machine runs the Intel XPU build of torch, where torch.cuda.is_available() is
    False and torch.xpu.is_available() is True. Colab will be the opposite. Any code that
    calls .cuda() directly will break on one of the two.

    torch is imported lazily so that analyze_labels.py, which needs no torch at all, does
    not pay for it just to read a path constant.
    """
    import torch

    if hasattr(torch, 'xpu') and torch.xpu.is_available():
        return 'xpu'
    if torch.cuda.is_available():
        return 'cuda'
    return 'cpu'
