"""Where things live on disk. Imported, never run.

Anchored to the repo root derived from this file's own location, so every script works
from any working directory.
"""

import os

REPO_ROOT = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))
DATASETS_DIR = os.path.join(REPO_ROOT, 'datasets')
OUTPUTS_DIR = os.path.join(REPO_ROOT, 'centerpoint', 'outputs')
EXAMPLES_DIR = os.path.join(DATASETS_DIR, 'examples')

# The dataset every script defaults to. v30 while developing: it is clean and easy, and
# YOLO26 reached 99.3% mAP50 on it, so a bad number there means a bug in our code rather
# than a hard image. Point this at bullet_rchsr/clean for real training, and pass that
# path explicitly before trusting any stride or sigma choice — see PLAN.md.
DATASET = os.path.join(DATASETS_DIR, 'bullet_holes', 'clean_v30')


def output_dir(*parts):
    """Path under centerpoint/outputs/, created if missing."""
    path = os.path.join(OUTPUTS_DIR, *parts)
    os.makedirs(path, exist_ok=True)
    return path


def dataset_name(dataset_root):
    """A filesystem-safe name for a dataset root, e.g. 'bullet_rchsr_clean'."""
    rel = os.path.relpath(os.path.abspath(dataset_root), DATASETS_DIR)
    if rel.startswith('..'):                       # a root outside datasets/
        rel = os.path.basename(os.path.abspath(dataset_root))
    return rel.replace(os.sep, '_')


def debug_dir(kind, dataset_root):
    """outputs/debug/<kind>/<dataset>/ — development artefacts, safe to delete wholesale.

    Everything under debug/ is regenerated by re-running the script that made it. Trained
    models and evaluation results will live elsewhere under outputs/, and are not
    disposable.

    The per-dataset level is not optional: without it two datasets' renders land in the
    same folder and silently mix, which is what happened the first time analyze_labels.py
    was run.
    """
    return output_dir('debug', kind, dataset_name(dataset_root))
